#!/usr/bin/env python

# Copyright 2014 William H. St. Clair
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import boto, boto.ec2, boto.exception

def main():
    argument_spec = ec2_argument_spec()

    argument_spec.update(
        dict(
            instance_id = dict(),
            eni_id = dict(),
            state = dict(default='present', choices=['absent', 'present'])
        )
    )
    module = AnsibleModule(argument_spec=argument_spec)

    instance_id = module.params['instance_id']
    eni_id = module.params['eni_id']
    state = module.params['state']

    ec2 = ec2_connect(module)


    try:
        instance = ec2.get_only_instances([instance_id])[0]
        attachment_id = None

        for i in instance.interfaces:
            if i.id == eni_id:
                attachment_id = i.attachment.id

        if state == "present":
            if attachment_id is not None:
                module.exit_json(changed=False, attachment_id=attachment_id)
            ec2.attach_network_interface(eni_id, instance_id, 1)
            module.exit_json(changed=True, attachment_id=attachment_id)
        elif state == "absent":
            if attachment_id is None:
                module.exit_json(changed=False)
            ec2.detach_network_interface(eni_id, instance_id, 1)
            module.exit_json(changed=True)

    except boto.exception.EC2ResponseError as e:
        module.fail_json(msg=e.message)

from ansible.module_utils.basic import *
from ansible.module_utils.ec2 import *

main()
